// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvDrBJULSJExO9ldubWZGDqvAx3Pebn5U',
    appId: '1:352031234862:web:6a91e1003d9fb1e2f5f8bf',
    messagingSenderId: '352031234862',
    projectId: 'vonc-ie',
    authDomain: 'vonc-ie.firebaseapp.com',
    storageBucket: 'vonc-ie.firebasestorage.app',
    measurementId: 'G-3ZVMFVR63E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2ostyBvx18wrVKOKEnL7onQd2NLti818',
    appId: '1:352031234862:android:0974c19aadd55428f5f8bf',
    messagingSenderId: '352031234862',
    projectId: 'vonc-ie',
    storageBucket: 'vonc-ie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRSpp47ohwvB_LaN5XV6oi86QS9zh8-ZA',
    appId: '1:352031234862:ios:8a86f34b0a16f152f5f8bf',
    messagingSenderId: '352031234862',
    projectId: 'vonc-ie',
    storageBucket: 'vonc-ie.firebasestorage.app',
    iosBundleId: 'com.example.voncIo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRSpp47ohwvB_LaN5XV6oi86QS9zh8-ZA',
    appId: '1:352031234862:ios:8a86f34b0a16f152f5f8bf',
    messagingSenderId: '352031234862',
    projectId: 'vonc-ie',
    storageBucket: 'vonc-ie.firebasestorage.app',
    iosBundleId: 'com.example.voncIo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvDrBJULSJExO9ldubWZGDqvAx3Pebn5U',
    appId: '1:352031234862:web:436ff2be29f1f5e7f5f8bf',
    messagingSenderId: '352031234862',
    projectId: 'vonc-ie',
    authDomain: 'vonc-ie.firebaseapp.com',
    storageBucket: 'vonc-ie.firebasestorage.app',
    measurementId: 'G-E9PBW0GY7K',
  );
}
